### ISSUE TITLE
toast.cancel()

### ISSUE THREAD

**Issue by lerendan** [yadav-rahul/TastyToast#15]
Hello , I think your TastyToast need a function of toast.cancel() .
I can't cancel the TastyToast when i close my activity or fragment , and i think a cancel of toast is important.
Thank's for your code , i like the TastyToast , it's beautiful

**Comment by yadav-rahul** [comment]
@lerendan Thanks for notifying about this. I am busy right now beacuse of my MTE coming. cancel feature will be added in the next version of TastyToast :)

**Comment by lerendan** [comment]
@yadav-rahul OK, have a good day

**Comment by yadav-rahul** [comment]
@lerendan This issue is fixed in version 0.1.1
