### ISSUE TITLE
About  Extendibility

### ISSUE THREAD

**Issue by WangXingjian** [yadav-rahul/TastyToast#16]
Hello,your Toast is great and I like it.But actually, sometimes I really want to move it to the center of the screen(And maybe some other changes anyway).So,hope that you can give users more methods to operate the Toast or just let it extends the native Toast~~~:）

**Comment by deelaka** [comment]
Agreed as it is, TastyToast is difficult to integrate into my app because the Toast's color does not fit with my apps background and it would be nice to center it. @yadav-rahul

**Comment by yadav-rahul** [comment]
@WangXingjian Actually purpose of `TastyToast` is only to customize the context of native android toast but you are welcomed if you want to implement it :)
