### ISSUE TITLE
魅蓝3s 无法使用

### ISSUE THREAD

**Issue by IAskWind** [yadav-rahul/TastyToast#18]
魅蓝3s 无法使用，demo运行后，不能使用

**Comment by yadav-rahul** [comment]
Can you elaborate it please?

**Comment by JarvanMo** [comment]
@yadav-rahul  MeiLan 3s can't run the demo.

**Comment by feisher** [comment]
原因是魅蓝3s不是正宗安卓系统，是阿里云系统，所以兼容性难免会出现问题

**Comment by yadav-rahul** [comment]
@feisher OK.
