### ISSUE TITLE
Duplication of toast messages

### ISSUE THREAD

**Issue by utaite** [yadav-rahul/TastyToast#19]
If the toast message is created in a short period of time, it is duplicated
Is there a way to solve it?

**Comment by yadav-rahul** [comment]
Can you elaborate it please?

**Comment by utaite** [comment]
In the case of LENGTH_SHORT, a toast message is displayed for two seconds.
However, if a toast message is called again in the meantime, it will not be immediately updated, but will be called after the previous toast message has disappeared.
How can I solve this problem?

**Comment by yadav-rahul** [comment]
@Utaite In the upcoming version of `TastyToast` you will be able to cancel exisiting toast. Stay tuned.

**Comment by utaite** [comment]
Thank you.
