### ISSUE TITLE
Error:converting bytecode to dex......

### ISSUE THREAD

**Issue by JiangShuLiang** [yadav-rahul/TastyToast#22]
The TastyToast is awesome! 
When I run my project then I got an exception,the detailed exception infomation is below.
do you know how to fix this problem.
Thx in advance.

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/facebook/rebound/AndroidSpringLooperFactory$ChoreographerAndroidSpringLooper$1;

Error:Execution failed for task ':app:transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by sal-git** [comment]
You might have two libraries of the same kind in your project. Remove any duplicates and do a clean build. 
[Might help](http://stackoverflow.com/questions/22468700/unexpected-top-level-exception-com-android-dex-dexexception-multiple-dex-files)
[Also here](http://stackoverflow.com/questions/21735493/com-android-dex-dexexception-multiple-dex-files-define)
[here too](http://stackoverflow.com/questions/29628067/com-android-dex-dexexception-multiple-dex-files-define-landroid-support-annotat)

**Comment by yadav-rahul** [comment]
@JiangShuLiang Is it working now?

**Comment by yadav-rahul** [comment]
@JiangShuLiang I am closing this issue for now. You can reopen it again if you want.
