### ISSUE TITLE
about the show time

### ISSUE THREAD

**Issue by arthasshi** [yadav-rahul/TastyToast#3]
as we know Toast and your TasyToast use the Toast_LOGIN or TOAST_SHORT to control the Toast show Time . 
Can we make it more intelligence ,put a long type parameter to control the show time? Or cancel it when I want.

**Comment by yadav-rahul** [comment]
thanks @arthasshi for giving me suggestions regarding the duration of toasts. I will think about implementing this feature in the next updated version of `TastyToast`.
