### ISSUE TITLE
 Multiple clicks appear too long

### ISSUE THREAD

**Issue by CherryLover** [yadav-rahul/TastyToast#4]
If you accidentally multi-point several times, really very uncomfortable experience
Forgive my English is bad, directly on the code.
`public static void showToast(Context context, String content) {
        if (toast == null) {
            toast = Toast.makeText(context, content, Toast.LENGTH_SHORT);
        } else {
            toast.setText(content);
        }
        toast.show();
    }`
I‘m learn from guolin

**Comment by yadav-rahul** [comment]
@CherryLover thanks for pitching your idea but see android has its own way of dealing with several toasts simultaneously. We can modify we it but then the basic experience of toast will be violated. 

Further I will consider your opinion and if it goes well then it will be updated in the next version of `TastyToast`.
