### ISSUE TITLE
i am developing an app  using TastyToast and i think there is a need for success Toast, so if you wan't i can do that for you

### ISSUE THREAD

**Issue by doomers** [yadav-rahul/TastyToast#5]

**Comment by yadav-rahul** [comment]
@rahul357 Thanks for showing interest in `TastyToast` but don't you think that success toast is already  there in it ([check this](https://github.com/yadav-rahul/TastyToast/blob/lib/static/success.gif))

**Comment by doomers** [comment]
Sorry i hasn't seen that..thanks
