### ISSUE TITLE
Make toasts customisable

### ISSUE THREAD

**Issue by UshalNaidoo** [yadav-rahul/TastyToast#6]
After looking through the code it seems like the toasts are quite hard coded, apart from the text it displays and the duration (which matches the normal toast duration of long (1) and short (0)).

Here are some suggestions so that others can begin to use this feature in their apps:
- [x] A default `TastyToast.show(text)` call that shows a default toast.
- [ ] Change the background color `TastyToast.show(text, #color)`
- [x] Pass in the duration in milliseconds, with a maximum bound
- [ ] Either pass in an image or an array of images to display the icon or a gif: `TastyToast.show(text, #color, #image)`, `TastyToast.show(text, #color, #image[])`

Just a few suggestions.

**Comment by yadav-rahul** [comment]
@UshalNaidoo If u want to do this part then you can do that.

Rahul Yadav

**Comment by UshalNaidoo** [comment]
I've created pull requests for 2 of those tasks, can you take a look at them, thanks
